name: frontend
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  get_it: ^7.6.4
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_staggered_animations: ^1.1.1
  intl: ^0.18.1
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/camera.png
    - assets/images/star.png
    - assets/images/star1.png
    - assets/images/screen0.png
    - assets/images/screen1.png
    - assets/images/screen2.png
    - assets/images/screen3.png
    - assets/images/screen4.png
    - assets/images/screen5.png
    - assets/elements/element1.png
    - assets/elements/element2.png
    - assets/elements/element3.png
    - assets/elements/element5.png
    - assets/elements/element6.png

  fonts:
    - family: Font
      fonts:
        - asset: assets/fonts/Fat Chubby Sans DEMO.otf
          weight: 400
    - family: Zatiyan
      fonts:
        - asset: assets/fonts/Zatiyan.ttf 

flutter_native_splash:
  image: assets/images/screen0.png
  color: "#5B00FF"
  android_12:
    image: assets/images/screen0.png
    icon_background_color: "#5B00FF"
  android: true
  ios: true
  web: true